<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE flights [
<!ELEMENT flights (flight*)>
<!ELEMENT flight (source, target)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT target (#PCDATA)>
]>
<flights>
    <flight>
        <source>Valencia (VLC)</source>
        <target>Londres Heathrow (LHR)</target>
    </flight>
    <flight>
        <source>Paris Charles from Gaulle (CDG)</source>
        <target>Berlin Sch√∂nefeld (SFX)</target>
    </flight>
</flights>